### PR TITLE
Move back to latexmlmath from latexmlc

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-standoc/issues/60

### CODE REVIEW

**Comment by opoudjis** [comment]
... So I can understand, @CAMOBAP795 : what does a Windows user need to do after installing Metanorma? They're not going to have to type "chcp 65001", are they?

**Comment by CAMOBAP795** [comment]
> what does a Windows user need to do after installing Metanorma? 

Type "chcp 65001" in windows' cmd before running metanorma command

I think we cannot automate this and change "chcp 65001" on system level because it maybe dangerous 

---

This is why I tried to use `latexmlc` because it have argument to provide input encoding

**Comment by opoudjis** [comment]
That... is... awful. I'm going to keep the source issue open.

**Comment by CAMOBAP795** [comment]
> That... is... awful. I'm going to keep the source issue open.

100% agree with you this is why I reported https://github.com/brucemiller/LaTeXML/issues/1111 and asked to add param `--inputencoding` to `latexmlmath`

**Comment by ronaldtse** [comment]
We ought to fix this... it's definitely a killer. And we have to document this in the Windows installation process. @CAMOBAP795 can you update the Windows installation instructions on https://github.com/metanorma/metanorma.com with a PR?

**Pull request merged**
