### PR TITLE
#96 do lazy latexml check

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #96

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you please help fix AppVeyor? Thanks.

**Comment by ronaldtse** [comment]
@CAMOBAP795 this is the failure in AppVeyor:

```
Failures:
638
639  1) Asciidoctor::Standoc processes the PlantUML macro with imagesdir
640     Failure/Error:
641       FileUtils.mv (Pathname.new(localdir) + "plantuml" + "#{fn}.png").to_s,
642         (Pathname.new(localdir) + outfile).to_s
643
644     Errno::ENOENT:
645       asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - No such file or directory @ rb_file_s_rename - (plantuml/431574da-d6d3-4123-b8db-fb07f23bca45.png, spec/assets/431574da-d6d3-4123-b8db-fb07f23bca45.png)
646     # ./lib/asciidoctor/standoc/macros.rb:95:in `generate_file'
647     # ./lib/asciidoctor/standoc/macros.rb:131:in `process'
648     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:1038:in `[]'
649     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:1038:in `build_block'
650     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:866:in `next_block'
651     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:369:in `next_section'
652     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:98:in `parse'
653     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:570:in `parse'
654     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `load'
655     # ./vendor/bundle/ruby/2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1479:in `convert'
656     # ./spec/asciidoctor-standoc/macros_spec.rb:100:in `block (2 levels) in <top (required)>'
657     # ------------------
658     # --- Caused by: ---
659     # Errno::ENOENT:
660     #   No such file or directory @ rb_file_s_rename - (plantuml/431574da-d6d3-4123-b8db-fb07f23bca45.png, spec/assets/431574da-d6d3-4123-b8db-fb07f23bca45.png)
661     #   ./lib/asciidoctor/standoc/macros.rb:95:in `generate_file'
662
663Finished in 14.37 seconds (files took 3.24 seconds to load)
664149 examples, 1 failure
665
666Failed examples:
667
668rspec ./spec/asciidoctor-standoc/macros_spec.rb:99 # Asciidoctor::Standoc processes the PlantUML macro with imagesdir
669
```

This is blocking https://github.com/metanorma/metanorma-cli/pull/108 too, could we fix this ASAP? Thanks.

**Comment by ronaldtse** [comment]
@CAMOBAP795 this spec is still failing on AppVeyor:

```
  1) Asciidoctor::Standoc processes the PlantUML macro with imagesdir
668     Failure/Error:
669       FileUtils.mv (Pathname.new(localdir) + "plantuml" + "#{fn}.png").to_s,
670         (Pathname.new(localdir) + outfile).to_s
671
672     Errno::ENOENT:
673       asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - No such file or directory @ rb_file_s_rename - (plantuml/afe7b70f-2ffc-4075-952b-c6f4af1cd6c3.png, spec/assets/afe7b70f-2ffc-4075-952b-c6f4af1cd6c3.png)
674     # ./lib/asciidoctor/standoc/macros.rb:95:in `generate_file'
675     # ./lib/asciidoctor/standoc/macros.rb:130:in `process'
676     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:1038:in `[]'
677     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:1038:in `build_block'
678     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:866:in `next_block'
679     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:369:in `next_section'
680     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:98:in `parse'
681     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:570:in `parse'
682     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `load'
683     # ./vendor/bundle/ruby/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1479:in `convert'
684     # ./spec/asciidoctor-standoc/macros_spec.rb:100:in `block (2 levels) in <top (required)>'
685     # ------------------
686     # --- Caused by: ---
687     # Errno::ENOENT:
688     #   No such file or directory @ rb_file_s_rename - (plantuml/afe7b70f-2ffc-4075-952b-c6f4af1cd6c3.png, spec/assets/afe7b70f-2ffc-4075-952b-c6f4af1cd6c3.png)
689     #   ./lib/asciidoctor/standoc/macros.rb:95:in `generate_file'
690
691Finished in 16.44 seconds (files took 4.3 seconds to load)
692149 examples, 1 failure
693
694Failed examples:
695
696rspec ./spec/asciidoctor-standoc/macros_spec.rb:99 # Asciidoctor::Standoc processes the PlantUML macro with imagesdir
697
```

Can you help? Thanks.

**Comment by ronaldtse** [comment]
@opoudjis but AppVeyor was failing. Are you sure you wanted to merge this?

**Comment by opoudjis** [comment]
Ah crap. 

@CAMOBAP795 I'm just going to wave changes like these through, and I thought this had fixed Appveyor. Without a usable dashboard, I have no way to make sense of these mods as a non-Windows user anyway.

Reverting.

**Comment by opoudjis** [comment]
Reverted. @CAMOBAP795, this remains open.

**Pull request merged**
