### PR TITLE
Feature/datamodel: re-implement, provide documentation

### PR DESCRIPTION
**Pull request by w00lf**
#116 

As discussed with @ronaldtse, created 2 separate macros:
- datamodel_attributes_table - renders attributes and values tables(if any exists) and description with yaml2text block
- datamodel_diagram - renders relation diagrams using erb template.
How it will look on  one of csd-digital-addresses files: csd-digital-addresses/sources/sections/08-data-types.adoc:

image

What are your thoughts on the new format @ronaldtse @opoudjis? If this is ok I will finish documentation for macro uses and create PR to csd-digital-addresses

### CODE REVIEW

**Comment by ronaldtse** [comment]
@w00lf looks good to me, please proceed with updates and PR. Thanks!

**Comment by ronaldtse** [comment]
@w00lf also, the Windows builds are failing due to sassc gem. Perhaps if the sassc gem is update to 2.4 it will be fixed.

**Comment by opoudjis** [comment]
Windows will indeed be resolved next release, isodoc upgraded to sassc 2.4.

**Comment by w00lf** [comment]
> Windows will indeed be resolved next release, isodoc upgraded to sassc 2.4.

Should I add sassc dependency to '~> 2.4' here?

**Comment by w00lf** [comment]
Added documentation entry for new syntax, dont quite know what should be in it except for yaml files format description and macros syntax, so i took Peter` docs and add macros descriptions. @ronaldtse @opoudjis can you please review it and tell what should be added - https://github.com/metanorma/metanorma-standoc/blob/feature/datamodel-reimplement/docs/datamodel.adoc?

**Comment by w00lf** [comment]
@ronaldtse @opoudjis created documentation entry in metanorma.com metanorma/metanorma.com#291

**Comment by ronaldtse** [comment]
@w00lf can you also help fix the Hound comments? Thanks.

**Comment by ronaldtse** [comment]
@w00lf we should use `datamodel_diagram` instead of `datamodel_plantuml`, can you fix?

**Comment by w00lf** [comment]
> datamodel_diagram

Done, changed

**Comment by w00lf** [comment]
@ronaldtse fixed most of the hound warnings except for the ones for specs. @ronaldtse @opoudjis what should I do with windows sassc specs failure? Ignore it as it will be fixed in release?

**Comment by opoudjis** [comment]
Yes

**Pull request merged**
