### PR TITLE
Move to GH Actions

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-build-scripts/issues/23

### CODE REVIEW

**Comment by ronaldtse** [comment]
Rebased, pending.

**Comment by ronaldtse** [comment]
@CAMOBAP795 Ubuntu is now passing. However these need to be fixed:

* LaTeXML spec is not working on macOS despite being installed (it doesn't process LaTeXML)
* LaTeXML is also not working on Windows

**Comment by ronaldtse** [comment]
Testing snap package for LaTeXML.

**Comment by ronaldtse** [comment]
@CAMOBAP795 This is still failing on macOS: 

```
LaTeXML not installed (or don't works properly). You must upgrade/install LaTeXML to  version
```

Can we fix this ASAP? Thanks.

**Comment by opoudjis** [comment]
Reminder to remove Appveyor here (and throughout Metanorma stack)

**Comment by CAMOBAP795** [comment]
Removed from appveyor

**Pull request merged**
