### PR TITLE
Remove `sassc` from gem runtime dependency

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/metanorma#109 moved sassc gem to dev dependency, temporarily added isodoc to Gemfile, added rake build script override.

### CODE REVIEW

**Comment by w00lf** [comment]
The new isodoc gem works correctly with scss only when the style file has the correct extension - .scss, old logic from specs with `css` file wont work, @opoudjis @ronaldtse would it be a problem?

**Comment by ronaldtse** [comment]
@w00lf then can we fix the old `.css` to `scss` extensions? Thanks!

**Comment by w00lf** [comment]
> @w00lf then can we fix the old `.css` to `scss` extensions? Thanks!

Yes, I have done this, works fine with that fix.

**Comment by ronaldtse** [comment]
Excellent, thanks!

**Pull request merged**
