### PR TITLE
Support for `lutaml_diagram` and `lutaml_datamodel_attributes_table` macroses, metanorma-plugin-lutaml

### PR DESCRIPTION
**Pull request by w00lf**
Depends on metanorma/metanorma-build-scripts#52

### CODE REVIEW

**Review by opoudjis — DISMISSED** [review]
I mean, not much here for me to review :)

**Comment by opoudjis** [comment]
````
--- Caused by: ---
384
     # NoMethodError:
385
     #   undefined method `serialized_document' for 10:Integer
386
     #   ./vendor/bundle/ruby/2.6.0/gems/metanorma-plugin-lutaml-0.2.0/lib/metanorma/plugin/lutaml/lutaml_datamodel_attributes_table_preprocessor.rb:52:in `parse_marco'
387
````

Hadn't seen: can't approve until rake test works...

**Comment by w00lf** [comment]
> ```
> --- Caused by: ---
> 384
>      # NoMethodError:
> 385
>      #   undefined method `serialized_document' for 10:Integer
> 386
>      #   ./vendor/bundle/ruby/2.6.0/gems/metanorma-plugin-lutaml-0.2.0/lib/metanorma/plugin/lutaml/lutaml_datamodel_attributes_table_preprocessor.rb:52:in `parse_marco'
> 387
> ```
> 
> Hadn't seen: can't approve until rake test works...

Forgot to add test file, fixed

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-standoc/pull/379/checks?check_run_id=1448473173 : not working on Windows

**Comment by ronaldtse** [comment]
And @w00lf probably `lutaml_datamodel_attributes_table` should be `lutaml_uml_attributes_table`?

**Comment by ronaldtse** [comment]
Here's the failed test on Windows now:

```
   <sections>
-    <figure id='_'>
-      <image src='spec/assets/_.png' id='_' mimetype='image/png' height='auto' width='auto'/>
-    </figure>
+    <sourcecode lang='lutaml' id='_'>diagram MyView { fontname "Arial" title "my diagram" class Foo {} }</sourcecode>
   </sections>
```

**Comment by w00lf** [comment]
> https://github.com/metanorma/metanorma-standoc/pull/379/checks?check_run_id=1448473173 : not working on Windows

That's because base iamge missing dot installation, I have created issue on that - https://github.com/metanorma/metanorma-build-scripts/issues/52

**Comment by w00lf** [comment]
> And @w00lf probably `lutaml_datamodel_attributes_table` should be `lutaml_uml_attributes_table`?

Done, renmaed the macro to `lutaml_uml_attributes_table`

**Comment by ronaldtse** [comment]
Thanks @w00lf !

**Pull request merged**
