### PR TITLE
Fix broken tests after e82be473

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis I'm 100% sure about the first commit, but not sure about second commit in this PR

**Comment by ronaldtse** [comment]
@CAMOBAP795 

AppVeyor failed on Ruby TRUNK (all other versions pass):
```
[!] There was an error parsing `Gemfile`: 
268[!] There was an error while loading `metanorma-standoc.gemspec`: syntax error, unexpected tLSHFT -   spec.description   = <<~DESCRIPTION
269                         ^
270C:/projects/metanorma-standoc/metanorma-standoc.gemspec:15: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
271    metanorma-standoc realises standards following the Meta...
272                              ^
273C:/projects/metanorma-standoc/metanorma-standoc.gemspec:17: syntax error, unexpected keyword_in, expecting keyword_end
274    This gem is in active development.
275                  ^. Bundler cannot continue.
276
277 #  from C:/projects/metanorma-standoc/metanorma-standoc.gemspec:14
278 #  -------------------------------------------
279 #    #spec.add_development_dependency "relaton-ietf"
280
```

Travis failed on Homebrew errors, restarted and let's see.

**Comment by ronaldtse** [comment]
@CAMOBAP795 it seems that the macOS builds are all failing at Homebrew installation:

https://travis-ci.org/metanorma/metanorma-standoc/jobs/589198046

```
/Users/travis/.travis/functions: line 553: 14619 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"
2588The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb ; fi" failed and exited with 1 during .
2589
2590
```

There's also this mention:
```
Still running (1 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (2 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (3 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (4 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (5 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (6 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (7 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (8 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (9 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (10 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (11 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (12 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb
Still running (13 of 20): brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb


[31;1mThe command brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb exited with 1.[0m



[32;1mLog:[0m



Warning: Your Xcode (9.4.1) is outdated.

Please update to Xcode 10.1 (or delete it).

Xcode can be updated from the App Store.



Warning: A newer Command Line Tools release is available.

Update them from Software Update in the App Store.

```

Maybe we have to update the Travis config to use a newer Xcode? Can you help fix this? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse I will check this

**Comment by CAMOBAP795** [comment]
Windows look ok https://ci.appveyor.com/project/Metanorma/metanorma-standoc/builds/27681128 but sometimes ImageMagic download failed(

**Pull request merged**
