### PR TITLE
Register extension Metanorma::Plugin::Lutaml::LutamlEaDiagramBlockMacro

### PR DESCRIPTION
**Pull request by kwkwan**
### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by kwkwan** [comment]
Refer to https://github.com/metanorma/metanorma-plugin-lutaml/pull/128, LutamlEaDiagramBlockMacro is needed to be registered in `metanorma-standoc`.

**Comment by kwkwan** [comment]
Do not merge this PR until `metanorma-plugin-lutaml` has been released.

**Comment by opoudjis** [comment]
metanorma-plugin-lutaml not release, so this is not making this release.

**Comment by ronaldtse** [comment]
Gem is released. @opoudjis please merge.

**Pull request merged**
